  name: Test on all platforms
  on:
    # This is configured to run on pull requests. If desired you can change it to run on all pushes.
    # be aware that windows and MacOS takes can take a while for setup and both of them incur extra expense for Actions.
    push:
    # this will allow the tests to be run on demand
    workflow_dispatch:
  
  env:
    GO_VERSION: 1.23

  jobs:
    test:
      name: Test on all platforms
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os:
            # - ubuntu-latest
            - macos-13
            # - windows-latest

      steps:
        - uses: actions/checkout@v4

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: ${{ inputs.terraform_version }}

        # - name: Install dependencies (macOS)
        #   if: runner.os == 'macos'
        #   run: |
        #     brew install lima qemu

        # - name: Start Lima VM (macOS)
        #   if: runner.os == 'macos'
        #   run: |
        #     limactl start
        #     limactl shell
        # - name: Set up Docker
        #   uses: docker/setup-docker-action@v4
        #   with:
        #     version: 'latest'
        - name: Setup Docker on macOS
          if: runner.os == 'macos'
          run: |
            export HOMEBREW_NO_AUTO_UPDATE=1
            brew install docker
            colima start --cpu 4 --memory 8 --vm-type=vz --mount-type=virtiofs

        # - name: Setup Docker on macOS
        #   uses: douglascamata/setup-docker-macos-action@v1-alpha

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3    



        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: ${{ env.GO_VERSION }}

        - name: Test
          run: go test ./...
