name: Test on all platforms
on:
  push:
  workflow_dispatch:

env:
  GO_VERSION: 1.23

jobs:
  test:
    name: Test on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-13
          - windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Setup Docker on macOS
        if: runner.os == 'macos'
        uses: douglascamata/setup-docker-macos-action@v1-alpha

      - name: Setup Docker on Ubuntu and Windows
        if: runner.os != 'macos'
        run: |
          if [[ ${{ matrix.os }} == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose
          elif [[ ${{ matrix.os }} == "windows-latest" ]]; then
            choco install docker-desktop
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test
        run: go test ./...
