
# name: Test on all platforms

# on:
#   push:  # Runs on every push
#   # pull_request:  # Runs on every PR
#   workflow_dispatch:  # Allows manual triggering

# env:
#   GO_VERSION: 1.23
#   terraform_version: 1.10.5


# jobs:
#   test:
#     name: Test on all platforms
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os:
#           # - ubuntu-latest
#           # - macos-13
#           - windows-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Install QEMU on Windows
#         if: matrix.os == 'windows-latest'
#         run: |
#           choco install qemu --yes
#           echo "C:\Program Files\qemu" >> $env:GITHUB_PATH

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: ${{ env.terraform_version }}

#       - name: Setup Docker on macOS
#         if: matrix.os == 'macos-13'  
#         uses: douglascamata/setup-docker-macos-action@v1-alpha    

#       - name: Set up QEMU (After Manual Installation)
#         uses: docker/setup-qemu-action@v2      

#       - name: Set up Go
#         uses: actions/setup-go@v5
#         with:
#           go-version: ${{ env.GO_VERSION }}

#       - name: Test
#         run: go test ./...
name: Test on all platforms
on:
  push:  # Runs on every push
  # pull_request:  # Runs on every PR
  workflow_dispatch:  # Allows manual triggering

env:
  GO_VERSION: 1.23
  terraform_version: 1.10.5


jobs:
  test:
    if: ${{ true }}
    name: Test on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{env.GO_VERSION}}

      - name: Test
        run: go test ./...