name: Test on all platforms

on:
  push:
  workflow_dispatch:

env:
  GO_VERSION: 1.23

jobs:
  test:
    name: Test on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          - macos-13
          # - windows-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      # Install dependencies and Docker on macOS
      - name: Install Docker on macOS
        if: runner.os == 'macos'
        run: |
          brew install lima docker
          limactl start docker
           limactl shell docker

      # # Start Docker on macOS (ensure daemon is running)
      # - name: Start Docker on macOS
      #   if: runner.os == 'macos'
      #   run: |
      #     open -a Docker
      #     sleep 30  # Wait for Docker to start

      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        # with:
        #   image: docker.io/tonistiigi/binfmt:latest
        #   platforms: all
        #   cache-image: true

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      # Run tests
      - name: Run Go tests
        run: go test ./...
