name: Test on all platforms

on:
  # This is configured to run on pull requests. If desired, you can change it to run on all pushes.
  # Be aware that Windows and macOS setup times can take a while and incur extra expense for Actions.
  push:
    # This will allow the tests to be run on demand
  workflow_dispatch:

env:
  GO_VERSION: 1.23

jobs:
  test:
    name: Test on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # Uncomment if you need to include Ubuntu or Windows.
          # - ubuntu-latest
          - macos-13
          # - windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      # Uncomment and configure this section if you want to install dependencies or start Lima VM for macOS
      # - name: Install dependencies (macOS)
      #   if: runner.os == 'macos'
      #   run: |
      #     brew install lima qemu

      # - name: Start Lima VM (macOS)
      #   if: runner.os == 'macos'
      #   run: |
      #     limactl start
      #     limactl shell

      # Set up Docker on macOS
      - name: Setup Docker on macOS
        if: runner.os == 'macos'
        run: |
           brew install docker docker-compose


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test
        run: go test ./...
